/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_derek_voicerchange_EffectUtil */

#ifndef _Included_com_derek_voicerchange_EffectUtil
#define _Included_com_derek_voicerchange_EffectUtil
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_derek_voicerchange_EffectUtil
 * Method:    fix_sound
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_derek_voicerchange_EffectUtil_fix_1sound
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
